### ISSUE TITLE
ISSUE WITH RESTORE BACKUP

### ISSUE THREAD

**Issue by fiqahmad** [uilibrary/Stocky-Issues-and-Feature-request#132]
Hi, Im having an issue after update . 

 I confused about the update mechanism , I mistakenly upload the whole file and lost the system. I deleted the whole system and reinstall again, I did my backup file and try to restore but failed to update my previous data.

Could you brief how to restore the backup file ? TQ

**Comment by hamzakifani** [comment]
where you uploaded stocky in localhost or server (cpanel) ???

**Comment by fiqahmad** [comment]
SERVER cpanel

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel access + backup database

**Comment by fiqahmad** [comment]
Done email

**Comment by hamzakifani** [comment]
we will fix this issue and let you know . thank you

**Comment by hamzakifani** [comment]
Hello .it's no data in your backup .

**Comment by fiqahmad** [comment]
That backup I generated from the' backup' function inside the system

**Comment by hamzakifani** [comment]
I think you generated a backup after upgrading to the new version 2.4.0 .  for that you forgot your data

**Comment by fiqahmad** [comment]
I generated before updated to new version. I dont know what im missing here. How many step backup i should make ? ,

**Comment by naime-hossain** [comment]
Please start with from new and we tried our best although this service is not included. 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
